version: "3.8"

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongodb
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  redis:
    image: redis:6-alpine
    container_name: api_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - web_api

  jaeger:
    container_name: jaeger_container
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - web_api

  mongodb:
    container_name: mongodb_container
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    networks:
      - web_api
networks:
  web_api:
    driver: bridge
